### ISSUE TITLE
Top 10 Table on Minigo page

### ISSUE THREAD

**Issue by john45678** [sethtroisi/cloudygo#23]
Could you add a top 10 models rating table on the minigo page?

**Comment by sethtroisi** [comment]
I'm working on a sorted option now, but I can expand the "best"/"worst" list in the short term

**Comment by sethtroisi** [comment]
http://cloudygo.com/v7-19x19/eval-graphs?sorted

You have to manually add "?sorted" but this sorts the eval table, more work to come tonight

**Comment by sethtroisi** [comment]
Top ten now appear by default in the list 
http://cloudygo.com/v3-9x9/eval-graphs

![screenshot from 2018-06-06 01-56-11](https://user-images.githubusercontent.com/10172976/41027791-d74e5726-692c-11e8-8412-cde0802e7076.png)
