### ISSUE TITLE
PV diagrams for models are broken when there are captures

### ISSUE THREAD

**Issue by amj** [sethtroisi/cloudygo#35]
![image](https://user-images.githubusercontent.com/422841/51052271-10eb3c00-158b-11e9-93ca-b9c293a8e353.png)

vs

![image](https://user-images.githubusercontent.com/422841/51052296-1c3e6780-158b-11e9-9bb9-87c6dc3a0dcf.png)

**Comment by sethtroisi** [comment]
From discord we found that I have an open TODO here: https://github.com/sethtroisi/cloudygo/blob/master/web/cloudygo.py#L1069
