### ISSUE TITLE
ringmaster games should store their comments

### ISSUE THREAD

**Issue by amj** [sethtroisi/cloudygo#37]
i think it involves supporting a custom GTP command; might involve being in minigo

**Comment by sethtroisi** [comment]
This will be fixed in CloudyGo https://github.com/sethtroisi/cloudygo/commit/55e44466916741f0fe8ac6ee993e85f02316d390#diff-990949ac35d65495e4cf2556c987bf98R258 and LZ pulling https://github.com/gcp/leela-zero/pull/2174
