### ISSUE TITLE
combined figure 3 graph?

### ISSUE THREAD

**Issue by amj** [sethtroisi/cloudygo#40]
is such a thing possible?  Making a combined fig3, and making the per-run fig3 only the zoom in at the tail?

**Comment by sethtroisi** [comment]
Done in https://github.com/sethtroisi/cloudygo/commit/d984ea8e27c75306a561bb85cd1ae96b4799df5d
![screenshot from 2019-01-29 02-40-43](https://user-images.githubusercontent.com/10172976/51902688-6ab37a80-236f-11e9-9fd0-0f9ef8914303.png)
