### ISSUE TITLE
it seems the Evaluation page of v16 paused

### ISSUE THREAD

**Issue by l1t1** [sethtroisi/cloudygo#42]
https://cloudygo.com/v16-19x19/eval-graphs
it shows 114380 games for a long time, and doesnt show new weights such as 1050

**Comment by l1t1** [comment]
https://cloudygo.com/ shows 1059 now

**Comment by sethtroisi** [comment]
Thanks for noticing. I'm investigating.

**Comment by sethtroisi** [comment]
Evaluation games weren't being added to the queue.
Fixed the issue and the backlog is being processed right now.

**Comment by l1t1** [comment]
and when will the v16 train finish?

**Comment by sethtroisi** [comment]
I think we're going to move on v17 in the next week so somewhere between 3 and 8 days

**Comment by l1t1** [comment]
what will the new things in v17? will it train from zero,or some weight from v16, or other methods?

**Comment by sethtroisi** [comment]
It will probably be a 20b Squeeze and Excitation network.
We always train from bootstrap weights (except for v13 which was an experiment)
