### ISSUE TITLE
could you test elfv2 vs minigo v15 m990

### ISSUE THREAD

**Issue by l1t1** [sethtroisi/cloudygo#44]
https://github.com/leela-zero/leela-zero/issues/2212

**Comment by sethtroisi** [comment]
when someone converts the weights we'll play some games

**Comment by sethtroisi** [comment]
https://cloudygo.com/ringmaster/minigo-converted-v-elf.report/

**Comment by l1t1** [comment]
from http://zero.sjeng.org/
v15m990 < elfv2 f185bf7a VS 05dbca15 0.32
v16m1144 < lz204 186898e8 VS 05d10f27 0.44
elfv2 <lz204 05dbca15 VS 05d10f27 0.35
according those result, can we conclude thant v16m1144>v15m990?
