### ISSUE TITLE
Add link to cross-run-eval

### ISSUE THREAD

**Issue by WhiteHalmos** [sethtroisi/cloudygo#50]
Context: https://github.com/tensorflow/minigo/issues/722#issuecomment-468059544

This issue tracks adding an endpoint for the cross-run-eval bucket that makes accessing 
https://cloudygo.com/all-eval-graphs?bucket=cross-run-eval possible through the UI.

**Comment by l1t1** [comment]
it looks v17 and v16 have similar strength

**Comment by sethtroisi** [comment]
I just made this the default for the 'all eval graph' link

**Comment by WhiteHalmos** [comment]
Horray! Thank you!
