### ISSUE TITLE
Can you please not using color to distinguish different line?

### ISSUE THREAD

**Issue by bjiyxo** [sethtroisi/cloudygo#52]
https://cloudygo.com/all-eval-graphs?bucket=cross-run-eval
Is there any way to show the cross-over graphic without only using color? For example, you can choose which line you want to show. For color blindness like me, I can hardly tell which is the corresponding one.

**Comment by sethtroisi** [comment]
Yes. Absolutely. Thanks for reaching out.
I'm travelling ATM but will fix when I'm back

**Comment by sethtroisi** [comment]
I tried to use d3 shapes but it looks very horrible.

I fell back to using toggles (as someone suggested in discord)
https://github.com/sethtroisi/cloudygo/commit/412b755ce6c370337492615cedb484dd1200f314

You may have to hard refresh the page to get static style to load.
Let me know if this doesn't work (or if you'd like something better)
