### ISSUE TITLE
put a download link on the eval game pages

### ISSUE THREAD

**Issue by amj** [sethtroisi/cloudygo#53]
Reported to me:  Person finds an interesting go game, but can't see a way to download the SGF from the page.  
Idea: a download link on the sgf-player page.

**Comment by sethtroisi** [comment]
https://cloudygo.com/cross-run-eval/10588/full/2019-03-14/1552571797-minigo-cc-evaluator-v15-747-vs-v17-594-wb-bnd8p-0-000747-bulldog-000594-opossum.sgf?raw=sgf&type=eval

**Comment by sethtroisi** [comment]
full changes to eval?
