### ISSUE TITLE
v15 hidden joseki?

### ISSUE THREAD

**Issue by barrtgt** [sethtroisi/cloudygo#55]
Using the new joseki page here https://cloudygo.com/v15-19x19/openings.html, I see all the openings for v15 are on a decline at the end of training. Is it somehow calculated differently or is there a dominating joseki that isn't showing up? Love the new tool btw.

**Comment by amj** [comment]
The joseki are sorted by the highest total during the whole run, so it's possible the most popular joseki at the end of the run aren't on the page.  It would be neat to do a 'most popular joseki at time t' page, but we haven't done it yet.

**Comment by barrtgt** [comment]
Ok that makes sense. I'll close the issue then.
