### ISSUE TITLE
Format Question

### ISSUE THREAD

**Issue by gleporeNARA** [sethtroisi/cloudygo#66]
I am working to create file format signatures for use in file identifications tools such as DROID and Siegfried. Can you please let me know what format the files on https://pminus1.cloudygo.com/ are? For example, https://pminus1.cloudygo.com/ download/m6918649

They have the initial four bytes of "K9z1", which is a decent enough magic to identify the files, but I like to have some additional information such as file format specifications, etc.

Thanks.

**Comment by sethtroisi** [comment]
These are save files from Prime95 (see https://www.mersenne.org/download/) 

The file format doesn't have a public specification but ostensible it is detailed in https://github.com/sethtroisi/misc-scripts/blob/main/mersenne/status_report/prime95_status.py#L40 where you can see the magic numbers 

```
>>> struct.pack("I", 0x317a394b)
b'K9z1'
```

**Comment by gleporeNARA** [comment]
Thank you, I will add that information and the sample files to my upcoming submission to the PRONOM database of file format signatures.
